/*
9. Write a JSP and Servlet Program to do the following to buy a T-Shirt online:
A set of checkboxes to select your T-Shirt accessories such as ‘belt’, ‘cap’, ‘hair-band’ , text area / text field to enter your T-Shirt tag-line,  Radio-button that allows the user to choose between T-Shirt with chest pocket and Combo Box to choose your T-Shirt color
Create appropriate labels for these GUI Components and a button called “Click Me” which when pressed will Insert the details entered into a table called ‘TShirts’. An OrderNo is generated by adding ‘1’ to the existing ‘OrderNo’. If ‘TShirts’ table is empty the initial value of ‘OrderNo’ is 100. This ‘OrderNo’ is also inserted into the ‘TShirts’ table . 
Display all the records of the ‘TShirts’ table in tabular form
PS: Frontend display should be in JSP and the business logic should be written in Servlet Class.
*/

import java.io.IOException;
import java.sql.DriverManager;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.sql.*;

/**
 * Servlet implementation class TShirt
 */
@WebServlet("/TShirt")
public class TShirt extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public TShirt() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		String accessories = request.getParameter("accessories");
		String tag = request.getParameter("tag");
		String chest = request.getParameter("chest");
		String color = request.getParameter("color");
		
		try{
			Class.forName("com.mysql.jdbc.Driver");
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javanew","root","anto");
			if(con != null){
				Statement st = con.createStatement();
				int  rs = st.executeUpdate("insert into tshirt (accessories, tag, chest, color) values('"+accessories+"','"+tag+"','"+chest+"','"+color+"')");
				response.sendRedirect("status.jsp?id=1");
				con.close();
				st.close();
			}else{
				response.sendRedirect("status.jsp?id=2");
			}
			
		}catch(ClassNotFoundException e){
			e.printStackTrace();
		}catch(SQLException e){
			e.printStackTrace();
			response.sendRedirect("status.jst?status=1");
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
